// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {character} from '../models';

export function GetCharacterData(arg1:string):Promise<character.Character>;

export function Greet(arg1:string):Promise<string>;
